/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author Cheeettoozzz
 */
public class Kalkulato1 extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulato1
     */
    String bilangan = "";
        double jumlah,bil1,bil2;
        int pilih;
    public Kalkulato1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_2 = new javax.swing.JButton();
        bt_3 = new javax.swing.JButton();
        bt_4 = new javax.swing.JButton();
        bt_5 = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        bt_7 = new javax.swing.JButton();
        bt_8 = new javax.swing.JButton();
        bt_9 = new javax.swing.JButton();
        bt_koma = new javax.swing.JButton();
        bt_1 = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        bt_0 = new javax.swing.JButton();
        bt_kurang = new javax.swing.JButton();
        bt_kali = new javax.swing.JButton();
        bt_clear = new javax.swing.JButton();
        bt_hasil = new javax.swing.JButton();
        txt_hasil = new javax.swing.JTextField();
        bt_bagi = new javax.swing.JButton();
        bt_log = new javax.swing.JButton();
        bt_sin = new javax.swing.JButton();
        bt_cos = new javax.swing.JButton();
        bt_tan = new javax.swing.JButton();
        bt_Mod = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_persen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 0));

        bt_2.setText("2");
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });

        bt_3.setText("3");
        bt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_3ActionPerformed(evt);
            }
        });

        bt_4.setText("4");
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });

        bt_5.setText("5");
        bt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5ActionPerformed(evt);
            }
        });

        bt_6.setText("6");
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });

        bt_7.setText("7");
        bt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_7ActionPerformed(evt);
            }
        });

        bt_8.setText("8");
        bt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_8ActionPerformed(evt);
            }
        });

        bt_9.setText("9");
        bt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_9ActionPerformed(evt);
            }
        });

        bt_koma.setText(".");
        bt_koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_komaActionPerformed(evt);
            }
        });

        bt_1.setText("1");
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });

        bt_tambah.setText("+");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_0.setText("0");
        bt_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_0ActionPerformed(evt);
            }
        });

        bt_kurang.setText("-");
        bt_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kurangActionPerformed(evt);
            }
        });

        bt_kali.setText("x");
        bt_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kaliActionPerformed(evt);
            }
        });

        bt_clear.setText("Clear");
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });

        bt_hasil.setText("=");
        bt_hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hasilActionPerformed(evt);
            }
        });

        txt_hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hasilActionPerformed(evt);
            }
        });

        bt_bagi.setText("/");
        bt_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bagiActionPerformed(evt);
            }
        });

        bt_log.setText("Log");
        bt_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logActionPerformed(evt);
            }
        });

        bt_sin.setText("Sin");
        bt_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sinActionPerformed(evt);
            }
        });

        bt_cos.setText("Cos");
        bt_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cosActionPerformed(evt);
            }
        });

        bt_tan.setText("Tan");
        bt_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tanActionPerformed(evt);
            }
        });

        bt_Mod.setText("MOD");
        bt_Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ModActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 36)); // NOI18N
        jLabel1.setText("KALKULATOR ");

        bt_persen.setText("%");
        bt_persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_persenActionPerformed(evt);
            }
        });

        jButton1.setText("Y^X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bt_1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(bt_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(bt_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(bt_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bt_kurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bt_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt_log, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_kali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt_cos))))
                            .addComponent(txt_hasil)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_koma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(bt_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_bagi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt_tan))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_Mod)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_persen)))))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_tambah)
                        .addComponent(bt_log))
                    .addComponent(bt_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_4)
                    .addComponent(bt_5)
                    .addComponent(bt_6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_kurang)
                        .addComponent(bt_sin)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_1)
                    .addComponent(bt_2)
                    .addComponent(bt_3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_kali)
                        .addComponent(bt_cos)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_0)
                    .addComponent(bt_koma)
                    .addComponent(bt_hasil)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_bagi)
                        .addComponent(bt_tan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_Mod)
                        .addComponent(bt_persen)
                        .addComponent(jButton1))
                    .addComponent(bt_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
        // TODO add your handling code here:

        bilangan +="2";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_2ActionPerformed

    private void bt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5ActionPerformed
        // TODO add your handling code here:

        bilangan +="5";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_5ActionPerformed

    private void bt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_8ActionPerformed
        // TODO add your handling code here:

        bilangan +="8";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_8ActionPerformed

    private void bt_komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_komaActionPerformed
        // TODO add your handling code here:
        bilangan +=".";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_komaActionPerformed

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        // TODO add your handling code here:

        bilangan +="1";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_1ActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:

        bil1 =Double.parseDouble(bilangan);
        txt_hasil.setText("+");
        bilangan="";
        pilih=1;  
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_0ActionPerformed
        // TODO add your handling code here:

        bilangan +="0";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_0ActionPerformed

    private void bt_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kurangActionPerformed
        // TODO add your handling code here:

        bil1 =Double.parseDouble(bilangan);
        txt_hasil.setText("-");
        bilangan="";
        pilih=2;  
    }//GEN-LAST:event_bt_kurangActionPerformed

    private void bt_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kaliActionPerformed
        // TODO add your handling code here:

        bil1 =Double.parseDouble(bilangan);
        txt_hasil.setText("*");
        bilangan="";
        pilih=3;  
    }//GEN-LAST:event_bt_kaliActionPerformed

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        // TODO add your handling code here:

        txt_hasil.setText(null);
        bil1=0.0;
        bil2=0.0;
        jumlah=0.0;
        bilangan="";
    }//GEN-LAST:event_bt_clearActionPerformed

    private void bt_hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hasilActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1+bil2;
            bilangan = Double.toString(jumlah);            
            break;
        case 2:
            bil2 =Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1 - bil2;
            bilangan = Double.toString(jumlah);            
            break;
        case 3:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1 * bil2;
            bilangan = Double.toString(jumlah);            
            break;
        case 4:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1 / bil2;
            bilangan = Double.toString(jumlah);            
            break;          
        case 5:           
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = (bil2 / 100) * bil2;
            bilangan = Double.toString(jumlah);
          break;
        case 6:
            
          bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
          jumlah = bil1%bil2;
          bilangan = Double.toString(jumlah);
          break;
        case 7:
          bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
         jumlah = Math.log(bil1);
         bilangan = Double.toString(jumlah);
         break;
        case 8:
         bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
         jumlah = Math.cos(bil1);
         bilangan = Double.toString(jumlah);
         break;
        case 9:
         bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
         jumlah = Math.tan(bil1);
         bilangan = Double.toString(jumlah);
         break;
        case 10:
         bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
         jumlah = Math.sqrt(bil1);
         bilangan = Double.toString(jumlah);
        } 
        
        txt_hasil.setText(bilangan);
        
    }//GEN-LAST:event_bt_hasilActionPerformed

    private void txt_hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hasilActionPerformed

    private void bt_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bagiActionPerformed
        // TODO add your handling code here:

        bil1 =Double.parseDouble(bilangan);
        txt_hasil.setText("/");
        bilangan="";
        pilih=4;  
    }//GEN-LAST:event_bt_bagiActionPerformed

    private void bt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_3ActionPerformed
        // TODO add your handling code here:

        bilangan +="3";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_3ActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
        // TODO add your handling code here:

        bilangan +="4";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
        // TODO add your handling code here:
        bilangan +="6";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_6ActionPerformed

    private void bt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_7ActionPerformed
        // TODO add your handling code here:

        bilangan +="7";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_7ActionPerformed

    private void bt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_9ActionPerformed
        // TODO add your handling code here:

        bilangan +="9";        
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_bt_9ActionPerformed

    private void bt_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sinActionPerformed
        // TODO add your handling code here:
        bil1=Double.parseDouble(bilangan);
        txt_hasil.setText(" Sin ");
        bilangan="";
        pilih=6;   
    }//GEN-LAST:event_bt_sinActionPerformed

    private void bt_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tanActionPerformed
        // TODO add your handling code here:
       bil1=Double.parseDouble(bilangan);
       txt_hasil.setText(" Tan ");
        bilangan="";
        pilih=9;
    }//GEN-LAST:event_bt_tanActionPerformed

    private void bt_ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ModActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bilangan);
        txt_hasil.setText("MOD");
        bilangan="";
        pilih=5;  
    }//GEN-LAST:event_bt_ModActionPerformed

    private void bt_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cosActionPerformed
        // TODO add your handling code here:
        bil1=Double.parseDouble(bilangan);
        txt_hasil.setText(" Cos ");
        bilangan="";
        pilih=8;
    }//GEN-LAST:event_bt_cosActionPerformed

    private void bt_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logActionPerformed
        // TODO add your handling code here:
        bil1=Double.parseDouble(bilangan);
        txt_hasil.setText(" Log ");
        bilangan=""; 
        pilih=7;
    }//GEN-LAST:event_bt_logActionPerformed

    private void bt_persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_persenActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(txt_hasil.getText());
        bilangan = "";
        jumlah = bil1 / 100 ;
        bilangan = Double.toString(jumlah);
        txt_hasil.setText(bilangan); 
    }//GEN-LAST:event_bt_persenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bil1=Double.parseDouble(bilangan);
        txt_hasil.setText(" Y^X ");
        bilangan=""; 
        pilih=10;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulato1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulato1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulato1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulato1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulato1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_0;
    private javax.swing.JButton bt_1;
    private javax.swing.JButton bt_2;
    private javax.swing.JButton bt_3;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_5;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_7;
    private javax.swing.JButton bt_8;
    private javax.swing.JButton bt_9;
    private javax.swing.JButton bt_Mod;
    private javax.swing.JButton bt_bagi;
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_cos;
    private javax.swing.JButton bt_hasil;
    private javax.swing.JButton bt_kali;
    private javax.swing.JButton bt_koma;
    private javax.swing.JButton bt_kurang;
    private javax.swing.JButton bt_log;
    private javax.swing.JButton bt_persen;
    private javax.swing.JButton bt_sin;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton bt_tan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_hasil;
    // End of variables declaration//GEN-END:variables
}
